version: "3.8"
services:
  api:
    container_name: api
    build: ./api
    environment: 
      PGHOST: db
      CORS_WHITELIST: ${CORS_WHITELIST:-http://localhost,http://localhost:3000}
      TOKEN_SECRET: ${TOKEN_SECRET:-CHANGE_ME}
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.5-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: perndb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  ui:
    container_name: ui
    build:
      context: ./ui
      args:
        REACT_APP_API: ${REACT_APP_API:-http://localhost:8080}
    environment: 
      PORT: 80
    command: nginx -g "daemon off";
    ports:
      - "80:80"
    depends_on: 
      - api
